#!/bin/sh

sleep_minutes=15

function cycle_pictures() {
    for FILE in $(ls ~/Pictures/Wallpaper/.feh_slideshow/* | shuf); 
    do 
        feh --bg-scale $FILE
        sleep $(( 60 * $sleep_minutes )) 
    done
    cycle_pictures
}

cycle_pictures
