require("core.plugin_config.catppuccin")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.nvim-treesitter")
require("core.plugin_config.telescope")
